In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
missing_values = ['N/a','na',np.nan]

In [3]:
df = pd.read_csv('train(loan).csv', na_values=missing_values)

In [4]:
df.head(2)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   
1  LP001003   Male     Yes          1  Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N

In [5]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
df.drop(['Loan_ID','Dependents','CoapplicantIncome','LoanAmount','Loan_Amount_Term'], axis = 1, inplace=True)

In [7]:
df.fillna(method='ffill', inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           614 non-null    object 
 1   Married          614 non-null    object 
 2   Education        614 non-null    object 
 3   Self_Employed    614 non-null    object 
 4   ApplicantIncome  614 non-null    int64  
 5   Credit_History   614 non-null    float64
 6   Property_Area    614 non-null    object 
 7   Loan_Status      614 non-null    object 
dtypes: float64(1), int64(1), object(6)
memory usage: 38.5+ KB


In [9]:
df.isnull().sum()

Gender             0
Married            0
Education          0
Self_Employed      0
ApplicantIncome    0
Credit_History     0
Property_Area      0
Loan_Status        0
dtype: int64

In [10]:
for i in df.columns:
    print(f'columns: {i}--------> unique_values: {df[i].nunique()}')

columns: Gender--------> unique_values: 2
columns: Married--------> unique_values: 2
columns: Education--------> unique_values: 2
columns: Self_Employed--------> unique_values: 2
columns: ApplicantIncome--------> unique_values: 505
columns: Credit_History--------> unique_values: 2
columns: Property_Area--------> unique_values: 3
columns: Loan_Status--------> unique_values: 2


In [11]:
df.columns

Index(['Gender', 'Married', 'Education', 'Self_Employed', 'ApplicantIncome',
       'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [12]:
df = pd.get_dummies(df, columns=['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area'], drop_first=True)

In [13]:
# sns.pairplot(df)

In [14]:
df['Loan_Status'] = np.where(df['Loan_Status']=="Y", 1, 0)

In [15]:
df.columns

Index(['ApplicantIncome', 'Credit_History', 'Loan_Status', 'Gender_Male',
       'Married_Yes', 'Education_Not Graduate', 'Self_Employed_Yes',
       'Property_Area_Semiurban', 'Property_Area_Urban'],
      dtype='object')

In [16]:
df = df[['ApplicantIncome', 'Credit_History', 'Gender_Male',
       'Married_Yes', 'Education_Not Graduate', 'Self_Employed_Yes',
       'Property_Area_Semiurban', 'Property_Area_Urban', 'Loan_Status']]

In [17]:
df.head()

ApplicantIncome  Credit_History  Gender_Male  Married_Yes  \
0             5849             1.0            1            0   
1             4583             1.0            1            1   
2             3000             1.0            1            1   
3             2583             1.0            1            1   
4             6000             1.0            1            0   

   Education_Not Graduate  Self_Employed_Yes  Property_Area_Semiurban  \
0                       0                  0                        0   
1                       0                  0                        0   
2                       0                  1                        0   
3                       1                  0                        0   
4                       0                  0                        0   

   Property_Area_Urban  Loan_Status  
0                    1            1  
1                    0            0  
2                    1            1  
3                    1            1  
4                    1            1

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ApplicantIncome          614 non-null    int64  
 1   Credit_History           614 non-null    float64
 2   Gender_Male              614 non-null    uint8  
 3   Married_Yes              614 non-null    uint8  
 4   Education_Not Graduate   614 non-null    uint8  
 5   Self_Employed_Yes        614 non-null    uint8  
 6   Property_Area_Semiurban  614 non-null    uint8  
 7   Property_Area_Urban      614 non-null    uint8  
 8   Loan_Status              614 non-null    int32  
dtypes: float64(1), int32(1), int64(1), uint8(6)
memory usage: 15.7 KB


In [19]:
X = df.drop('Loan_Status', axis = 1).values
y = df['Loan_Status'].values

In [20]:
X.shape

(614, 8)

In [21]:
y.shape

(614,)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [24]:
# from sklearn.ensemble import ExtraTreesRegressor

In [25]:
# model = ExtraTreesRegressor()

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model = LogisticRegression()

In [28]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
prediction = model.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, classification_report, explained_variance_score

In [31]:
print(explained_variance_score(y_test,prediction))

0.09684917355371925


In [32]:
print(confusion_matrix(y_test,prediction))

[[ 27  37]
 [  6 115]]


In [33]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.82      0.42      0.56        64
           1       0.76      0.95      0.84       121

    accuracy                           0.77       185
   macro avg       0.79      0.69      0.70       185
weighted avg       0.78      0.77      0.74       185



In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
Dclf = DecisionTreeClassifier()

In [36]:
Dclf.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [37]:
prediction1 = Dclf.predict(X_test)

In [38]:
prediction1

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0])

In [39]:
print(classification_report(y_test,prediction1))

              precision    recall  f1-score   support

           0       0.56      0.55      0.56        64
           1       0.76      0.78      0.77       121

    accuracy                           0.70       185
   macro avg       0.66      0.66      0.66       185
weighted avg       0.70      0.70      0.70       185



In [40]:
print(confusion_matrix(y_test,prediction1))

[[35 29]
 [27 94]]


In [52]:
df.iloc[1]

ApplicantIncome            4583.0
Credit_History                1.0
Gender_Male                   1.0
Married_Yes                   1.0
Education_Not Graduate        0.0
Self_Employed_Yes             0.0
Property_Area_Semiurban       0.0
Property_Area_Urban           0.0
Loan_Status                   0.0
Name: 1, dtype: float64

In [54]:
Dclf.predict([[4583,1,1,1,0,0,0,0]]) # its provide most accurate output

array([0])

In [55]:
model.predict([[4583,1,1,1,0,0,0,0]])

array([1])

In [56]:
import pickle

In [58]:
pickle.dump(Dclf, open('Loan(Y,N).pkl', 'wb'))